### PR TITLE
Change eslint to use local dependencies

### PR DESCRIPTION
**Pull request by hellowin**
I have no idea is it better or not since on my local it's both exited with an error. I prefer to use local dependencies since the user will not necessary to install global package of eslint.

### CODE REVIEW

**Comment by sonnylazuardi** [comment]
@hellowin what is estraverse-fb?

**Comment by hellowin** [comment]
Actually I have no idea, the `linter` just needed it (but still error, exited non zero code).

**Comment by pveyes** [comment]
Actually npm will use PATH from `node_modules/.bin` if you use npm script `npm run [something]` so `eslint` command can be written without using `node_modules/.bin/eslint`

About eslint error, it's because eslint originally use `estraverse-fb` (which is used by `babel-eslint` to monkeypatch the AST to know about flowtype declaration), but they dropped it in eslint 2.4 (hence it  breaks on recent version of eslint). The fix is quite easy, just replace babel-eslint to version 6, no need to install estraverse-fb

Hope this helps cc @sonnylazuardi @hellowin

**Comment by hellowin** [comment]
@pveyes thank you for your information. I already push another commit, now linter is already function and returns no error (actually I still have no idea it's works or not, lol).

But `npm run eslint` nor `npm run eslint.js` both did not work @pveyes that's why I still put `./node_modules/eslint/bin/eslint.js` on the script runner.

**Comment by pveyes** [comment]
@hellowin I think you specify the wrong command, it should be `npm run lint`, see [here](https://github.com/reactjs-id/react-webpack-starter/blob/master/package.json#L9)

**Comment by hellowin** [comment]
oooh ic ic

**Pull request closed without merging**
